# Copyright 2018 James E. King III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

sudo: false
dist: trusty
language: cpp

script:
  - make test

notifications:
  email:
    false
