#
# Copyright 2022 James E. King III
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
# The prereleased type release event does the heavy lifting: build and push
# The released type release event simply re-tags as latest
#
---
name: Release

on:
  release:
    types:
      - prereleased
      - released

jobs:
  release:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - { distro: ubuntu, edition: focal, arch: x86_64 }
          - { distro: ubuntu, edition: focal, arch: arm64  }
          - { distro: fedora, edition: 34,    arch: s390x  }

    timeout-minutes: 45
    runs-on: ubuntu-latest
    env:
      BDDE_DISTRO: ${{ matrix.distro }}
      BDDE_EDITION: ${{ matrix.edition }}
      BDDE_ARCH: ${{ matrix.arch }}
      BDDE_REBUILD: 1

    steps:
      - uses: actions/checkout@v2

      - name: Enable multiarch
        if: github.event.release.prerelease
        run: |
          sudo apt-get install -y binfmt-support qemu-user-static
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          echo "$(pwd)/bin/linux" >> $GITHUB_PATH

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        if: github.event.release.prerelease
        run: bdde-build

      - name: Prerelease Image
        if: github.event.release.prerelease
        run: |
          source bin/linux/lib/defaults.sh
          docker image tag "${{ github.repository }}:${BDDE_SLUG}" "${{ github.repository }}:${BDDE_SLUG}.${{ github.ref_name }}"
          docker push "${{ github.repository }}:${BDDE_SLUG}.${{ github.ref_name }}"

      - name: Release Image
        if: "!github.event.release.prerelease"
        run: |
          source bin/linux/lib/defaults.sh
          docker pull "${{ github.repository }}:${BDDE_SLUG}.${{ github.ref_name }}"
          docker image tag "${{ github.repository }}:${BDDE_SLUG}.${{ github.ref_name }}" "${{ github.repository }}:${BDDE_SLUG}"
          docker push "${{ github.repository }}:${BDDE_SLUG}"
